### PR TITLE
Minor improvements before fix release

### PR DESCRIPTION
**Pull request by fjvallarino**
- Adds `pointToLineDistance` utility function
- Restricts `toggleButton`'s type argument for configuration options to Bool (the only valid type)
- Avoids drawing borders if width == 0
- Updates default style for tooltip widget

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
Is it possible to get an optional(?) caret for tooltip? Forgot to ask this before.

**Comment by fjvallarino** [comment]
@MuhammedZakir no, `tooltip` is for informational content only and works similarly to `label` (i.e., just renders text). You will soon be able to implement a custom solution with a `popup` and a read-only `textField`.

I plan to allow arbitrary content in `tooltip`, which would enable you to do the same I suggest above, but it's very low in priority and will take a while before I get to it.

**Comment by MuhammedZakir** [comment]
I think we are talking about different things? What I meant by caret is the triangle thing seen just near the tooltip's border.

E,g, https://www.carbondesignsystem.com/components/tooltip/style

**Comment by fjvallarino** [comment]
Could you create a separate issue for this? Issues are easier to track, and the question is not related to the PR.

**Pull request merged**
