### PR TITLE
Fix compatibility with GHC 9.2.2 (issue #159)

### PR DESCRIPTION
**Pull request by Dretch**
I'm not sure what the compilation error really meant... but this seems to fix it.

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
This seems more correct to me:

```diff
diff --git a/src/Monomer/Widgets/Containers/Dropdown.hs b/src/Monomer/Widgets/Containers/Dropdown.hs
index 17bd6eac..ea999648 100644
--- a/src/Monomer/Widgets/Containers/Dropdown.hs
+++ b/src/Monomer/Widgets/Containers/Dropdown.hs
@@ -254,7 +254,7 @@ dropdownD_ widgetData items makeMain makeRow configs = newNode where
     & L.info . L.focusable .~ True
 
 makeDropdown
-  :: (WidgetModel s, WidgetEvent e, DropdownItem a)
+  :: forall s e a . (WidgetModel s, WidgetEvent e, DropdownItem a)
   => WidgetData s a
   -> Seq a
   -> (a -> WidgetNode s e)
@@ -420,9 +420,11 @@ makeDropdown widgetData items makeMain makeRow config state = widget where
       & L.widget .~ makeDropdown widgetData items makeMain makeRow config newState
     requests = [ResetOverlay slWid, SetFocus widgetId]
 
+  scrollListInfo :: WidgetNode s e -> (WidgetId, Path)
   scrollListInfo node = (scrollInfo ^. L.widgetId, scrollInfo ^. L.path) where
     scrollInfo = node ^?! L.children . ix listIdx . L.info
 
+  selectListInfo :: WidgetNode s e -> (WidgetId, Path)
   selectListInfo node = (listInfo ^. L.widgetId, listInfo ^. L.path) where
     listInfo = node ^?! L.children . ix listIdx . L.children . ix 0 . L.info
 
```

---

If it helps: how I came to this solution:
- I enabled the extension mentioned by GHC. I did this because I heard that a major GHC-version bump may make adding an extension (un)necessary which was previously (un)necessary.
- When I added it, I got the error shown in #_1_. Searching it lead me to below 2 links.

1. https://stackoverflow.com/questions/12719435/what-are-skolems
2. https://stackoverflow.com/questions/33066635/haskell-are-type-variables-in-where-clauses-in-the-same-namespace-with-their

**Comment by fjvallarino** [comment]
I think the `forall` version is preferable since we can make sure the types used by those functions are the same as the whole widget instance uses. I'm fine either way since it is something internal.

Regarding the SDL2 issue, does this happen only on GHC 9.2? No problem with using the commit hash meanwhile, of course.

Also reported here: https://github.com/fjvallarino/monomer/issues/159

**Review by fjvallarino — APPROVED** [review]
@Dretch looks good! 👍

**Comment by fjvallarino** [comment]
> I'm not really sure how to handle this in Haskell land. The stack.yaml that comes with monomer uses lts-18.27 (ghc-8.10.7) so the examples of course run without issue and therefore I'm not sure it is helpful to put the commit-hash version of SDL2 in there. If someone googles the error they will probably end up here, so maybe that is enough!?

I guess you're right. Since the current LTS is 18.27, we're safe in the case of new users. In case somebody ventures to build using 9.2 and report the problem, I can point them to your PR so they can use the correct version. I assume most people using 9.2 use Cabal instead of Stack (the nightlies give several versioning errors).

**Comment by fjvallarino** [comment]
Thanks for the fix!

**Pull request merged**
