### PR TITLE
Add WidgetButton

### PR DESCRIPTION
**Pull request by prolic**
This PR adds a widget button. The "normal" button allows only a text caption. With this new extension it's possible to make a button out of every existing widget.

### CODE REVIEW

**Comment by prolic** [comment]
ping @fjvallarino

**Comment by prolic** [comment]
Ah there is onClick for a box_? Then this is indeed not needed. I'll
double check

**Comment by prolic** [comment]
Stupid me: I already used `box_` with `onClick` in my project, forgot about it and then added this mess instead, lol.

**Comment by fjvallarino** [comment]
@prolic sorry for the long delay; been dealing with personal issues and may not be as responsive as usual for a couple more weeks.

One problem with using `button` instead of `box` is that it includes default styling based on the current theme; in most cases, you would need to disable it, providing `ignoreTheme` as a configuration flag. Another issue is that styling can become a bit of a nightmare since the current implementation is quite tightly tied to `label` (it passes down styling options in a way that avoids these issues). While demanding a bit more effort, I think using `box` is more explicit regarding what you can expect, instead of finding limitations or weird behavior.

One missing thing in `box` is that when marked as _focusable_, it does not respond to Enter/Space when it has focus. I intended this to be handled by a wrapper `keystroke` widget, but I guess it's more intuitive if it works that way out of the box. I'll think about it a bit and push changes.

**Pull request closed without merging**
