### PR TITLE
github/actions (Linux): add automated builds+tests

### PR DESCRIPTION
**Pull request by smunix**
Build and validate the tests on each PR using gh/actions

### CODE REVIEW

**Comment by smunix** [comment]
It fails with
```sh
       > error: XDG_RUNTIME_DIR not set in the environment.
       > monomer-test: SDLCallFailed {sdlExceptionCaller = "SDL.Init.init", sdlFunction = "SDL_Init", sdlExceptionError = "No available video device"}
```
Closing this PR!

**Comment by fjvallarino** [comment]
@smunix this is nice! I think `xvfb-run` will be needed for the tests to run. The one mentioned [here](https://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html), or something similar.

**Comment by smunix** [comment]
> @smunix sorry for the delay. I was checking the logs, but I'm not sure if the tests are being run. I see this:
> 
> ```
> Running 1 test suites...
> Test suite monomer-test: RUNNING...
> Test suite monomer-test: PASS
> Test suite logged to: dist/test/monomer-1.0.0.2-monomer-test.log
> 1 of 1 test suites (1 of 1 test cases) passed.
> ```
> 
> But I'm not sure if the logs for tests are available for download too. I guess they're being executed since they failed previously.

Indeed, all tests are executed. We shouldn't need to look into the test artifacts, unless any test fails. In that case, the test outputs are available. See [smunix:monomer/ubuntu-latest-monomer.log](https://github.com/smunix/monomer/suites/3619707613/artifacts/87520143) for example, where I purposefully broke one of the tests.

break-test

**Comment by fjvallarino** [comment]
@smunix looks great! Thanks!

**Pull request merged**
